repos:
- repo: local
  hooks:
    - id: update-doc
      name: update-doc
      entry: ./scripts/swagger.sh create_doc
      language: script
      verbose: true
      always_run: true
    - id: validate-doc
      name: validate-doc
      entry: ./scripts/swagger.sh validate_doc
      language: script
      always_run: true